quarkus.hibernate-orm.schema-management.strategy=update
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=admin
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres
#quarkus.datasource.driver=org.postgresql.Driver

quarkus.oidc.auth-server-url=http://localhost:8080/realms/stdsec-la-realm
quarkus.oidc.client-id=stdsec-la-api
quarkus.oidc.credentials.secret=erDWEPZP1PE06IFXdSA28tfAQyzr7lwx
quarkus.http.port=8081