quarkus.hibernate-orm.schema-management.strategy=validate
quarkus.flyway.migrate-at-start=true
quarkus.hibernate-orm.log.sql=true
quarkus.datasource.devservices.enabled=false
%test.quarkus.datasource.devservices.enabled=false

quarkus.http.auth.permission.api.paths=/api/*
quarkus.http.auth.permission.api.policy=authenticated
quarkus.http.auth.permission.api.priority=1

quarkus.http.auth.permission.front.paths=/*
quarkus.http.auth.permission.front.policy=permit
quarkus.http.auth.permission.front.priority=2


# Désactive la datasource pour l?instant
#quarkus.datasource.enabled=false
#quarkus.hibernate-orm.enabled=false
#%test.quarkus.datasource.enabled=false

#deactivate keycloak while deving
quarkus.oidc.enabled=false
